Vu/handle fork choice
gonative-cc/bitcoin-lightclient pull request #6
Opened 2024-10-25 16:46 UTC by vuvoth

2024-10-29 13:20 UTC, vuvoth commented on btc_light_client_store.go
> +	// "math/big"
```suggestion
	// "math/big"
```

2024-10-29 13:20 UTC, vuvoth commented on btc_light_client_store.go
> +	// "math/big"
```suggestion
```

2024-10-29 13:28 UTC, vuvoth commented on btc_light_client_store.go
>  func (s *MemStore) LatestHeight() int64 {
Seem likes LatestHeight name is no sense since this function is get height of the latest checkpoint or latest finalize block.

2024-11-08 13:32 UTC, robert-zaremba requested changes
* `extractFork` function is wrong - see comments.
* Please add tests - this way you make sure the code works
* I suggested few renames to make the code more clear.

2024-11-08 13:32 UTC, robert-zaremba commented on btc_light_client.go
> +func (lc *BTCLightClient) InsertHeaders(header wire.BlockHeader) error {
```suggestion
func (lc *BTCLightClient) InsertHeader(header wire.BlockHeader) error {
```

2024-11-08 13:32 UTC, robert-zaremba commented on btc_light_client.go
> +	if lc.btcStore.RemindFork(previousBlockHash) {
```suggestion
	if lc.btcStore.IsForkHead(previousBlockHash) {
```

2024-11-08 13:32 UTC, robert-zaremba commented on btc_light_client.go
> +	previousBlock := lc.btcStore.LightBlockByHash(previousBlockHash)
```suggestion
	parentHash := header.PrevBlock
	parent := lc.btcStore.LightBlockByHash(previousBlockHash)
```

2024-11-08 13:32 UTC, robert-zaremba commented on btc_light_client.go
> +		if err := lc.CheckHeader(previousHeader, header); err != nil {
```suggestion
		if err := lc.CheckHeader(parent.Header, header); err != nil {
```

2024-11-08 13:32 UTC, robert-zaremba commented on btc_light_client.go
>  	}
```suggestion
	fork := make([]*LightBlock, 0)
	for count := 0; count <= MaxForkAge; count++ {
		curr := lc.btcStore.LightBlockByHash(bh)
		fork = append(fork, curr)
		if bh.IsEqual(&checkpointHash) {
			return fork, nil
		}
		bh = curr.Header.PrevBlock
	}
```

2024-11-08 13:32 UTC, robert-zaremba commented on btc_light_client.go
> +func (lc *BTCLightClient) extractFork(bh chainhash.Hash) ([]*LightBlock, error) {
```suggestion
func (lc *BTCLightClient) findLightBlock(bh chainhash.Hash) ([]*LightBlock, error) {
```

2024-11-08 13:32 UTC, robert-zaremba commented on btc_light_client.go
> +	checkpoint := lc.btcStore.LatestCheckPoint()
There can be few heads. Example, where we have 3 active forks, with 3 latest blocks (b3, c3, d3):
```
b1 <- b2  <- b3
   |- c2  <- c3
   |- d2'  <- d3
```

2024-11-08 13:32 UTC, robert-zaremba commented on btc_light_client.go
> +	return nil, errors.New("Fork age invalid")
```suggestion
	return nil, errors.New("Block not found or too old")
```

2024-11-08 15:11 UTC, robert-zaremba approved these changes

2024-11-08 15:12 UTC, merged